/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AnyForm {
    /**
    * The first name
    */
    'collection': string;
  }
}

declare global {


  interface HTMLAnyFormElement extends Components.AnyForm, HTMLStencilElement {}
  var HTMLAnyFormElement: {
    prototype: HTMLAnyFormElement;
    new (): HTMLAnyFormElement;
  };
  interface HTMLElementTagNameMap {
    'any-form': HTMLAnyFormElement;
  }
}

declare namespace LocalJSX {
  interface AnyForm {
    /**
    * The first name
    */
    'collection'?: string;
  }

  interface IntrinsicElements {
    'any-form': AnyForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'any-form': LocalJSX.AnyForm & JSXBase.HTMLAttributes<HTMLAnyFormElement>;
    }
  }
}


